sudo: required
services: 
    - docker

before_install:
    - docker build -t timmanas/DockerProdFlowExample -f Dockerfile.dev .

script:
    - docker run timmanas/DockerProdFlowExample npm run test -- --coverage

