sudo: required
services: 
    - docker

before_install:
    - docker build -t timmanas/dockerprodflowexample -f Dockerfile.dev .

script:
    - docker run timmanas/dockerprodflowexample npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "DockerProdFlowExample"
    env: "Dockerprodflowexample-env"
    bucket_name: "elasticbeanstalk-us-east-2-578771921771"
    bucket_path: "DockerProdFlowExample"
    on:
        branch: master
    access_key_id: $access_key_id
    secret_access_key:
        secure: "$secret_access_key"